server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-services
          uri: https://github.com/caginer/microservicios
          search-paths: config-data
  application:
    name: config-service
